// pages/media.vue
<script setup lang="ts">
import { ref, watch, onMounted } from "vue";
import { toast } from "vue-sonner";
import { Loader2 } from "lucide-vue-next";
import type { tbm_media } from "@prisma/client";
import moment from "moment";

const fileInput = ref<HTMLInputElement | null>(null);
const loading = ref(false);
const err_message = ref<string | null>(null);

const onUpload = () => {
  fileInput.value?.click();
};

const handleFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  const formData = new FormData();
  formData.append("file", file);

  loading.value = true;
  err_message.value = null;

  try {
    const result = await toast.promise(
      fetch("/api/media/upload", {
        method: "POST",
        body: formData,
      }).then(async (response) => {
        if (!response.ok) throw new Error("Upload failed");
        return await response.json();
      }),
      {
        loading: "Uploading file...",
        success: "Upload successful!",
        error: (err: Error) => err.message || "Upload failed",
      }
    );

    console.log("Upload success:", result);
    await fetchMedia(); // Refresh after upload
  } catch (err) {
    console.error("Upload error:", err);
  } finally {
    loading.value = false;
    target.value = ""; // reset input
  }
};

const formatSize = (size: number) => {
  if (size < 1024) return `${size} B`;
  else if (size < 1024 * 1024) return `${(size / 1024).toFixed(2)} KB`;
  else if (size < 1024 * 1024 * 1024)
    return `${(size / (1024 * 1024)).toFixed(2)} MB`;
  else return `${(size / (1024 * 1024 * 1024)).toFixed(2)} GB`;
};

const data = ref<tbm_media[]>([]);
const dataActive = ref<tbm_media | null>(null);

// 🔍 Search
const search = ref("");

// 📦 Pagination
const pagination = ref({
  total: 0,
  page: 1,
  limit: 5,
  lastPage: 1,
});

// 📡 Fetch data from API
const fetchMedia = async () => {
  try {
    const response = await $fetch("/api/media", {
      params: {
        page: pagination.value.page,
        limit: pagination.value.limit,
        search: search.value || undefined,
      },
    });

    if (response) {
      (data as any).value = response.data;
      (dataActive as any).value = response.data[0] || null;

      pagination.value = {
        total: response.pagination.total,
        page: response.pagination.page,
        limit: response.pagination.limit,
        lastPage: response.pagination.lastPage,
      };
    } else {
      err_message.value = "Failed to fetch media";
    }
  } catch (err) {
    console.error("Fetch media error:", err);
    err_message.value = "Something went wrong while fetching media.";
  }
};

onMounted(() => {
  fetchMedia();
});

watch(
  () => pagination.value.page,
  () => {
    fetchMedia();
  }
);

// 🔄 Watch search and reset page
watch(search, () => {
  pagination.value.page = 1;
  fetchMedia();
});
</script>

<template>
  <div class="w-full flex flex-col items-stretch gap-4">
    <!-- Header -->
    <div class="flex flex-wrap items-end justify-between gap-2">
      <div>
        <h2 class="text-2xl fw-600 tracking-tight">Manage Media</h2>
        <p class="text-muted-foreground">
          Manage your media files, including images, videos, and audio files.
          You can upload, delete, and organize your media files in this section.
        </p>
      </div>
    </div>

    <!-- Upload Button -->
    <div>
      <Button size="sm" @click="onUpload" :disabled="loading">
        <Icon name="lucide:cloud-upload" class="mr-2" />
        Upload Media
        <Loader2 v-if="loading" class="ml-2 h-4 w-4 animate-spin" />
      </Button>
      <input
        ref="fileInput"
        type="file"
        accept="image/*,video/*,audio/*"
        class="hidden"
        @change="handleFileChange"
      />
    </div>

    <!-- Grid Layout -->
    <div class="grid grid-cols-12 gap-4 border-t pt-5">
      <!-- Media Table -->
      <div class="col-span-12 lg:col-span-8">
        <div class="flex justify-between mb-5">
          <div class="flex items-center gap-2">
            <Input
              v-model="search"
              type="text"
              placeholder="Search media..."
              class="w-full max-w-[400px] outline-none"
            />
          </div>

          <Pagination
            v-slot="{ page }"
            :items-per-page="pagination.limit"
            :total="pagination.total"
            :sibling-count="1"
            :page="pagination.page"
            show-edges
            :default-page="pagination.page"
            @update:page="
              (p) => {
                pagination.page = p;
              }
            "
          >
            <PaginationList v-slot="{ items }" class="flex items-center gap-1">
              <!-- <PaginationFirst /> -->
              <PaginationPrev />

              <template v-for="(item, index) in items">
                <PaginationListItem
                  v-if="item.type === 'page'"
                  :key="index"
                  :value="item.value"
                  as-child
                >
                  <Button
                    class="w-9 h-9 p-0"
                    :variant="item.value === page ? 'default' : 'outline'"
                  >
                    {{ item.value }}
                  </Button>
                </PaginationListItem>
                <PaginationEllipsis v-else :key="item.type" :index="index" />
              </template>

              <PaginationNext />
              <!-- <PaginationLast /> -->
            </PaginationList>
          </Pagination>
        </div>

        <div class="max-h-[70vh] overflow-y-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Filename</TableHead>
                <TableHead>Format</TableHead>
                <TableHead>File Size</TableHead>
                <TableHead>Image Size</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <!-- Loading State -->
              <TableRow v-if="loading">
                <TableCell colspan="4" class="text-center py-10">
                  <Loader2 class="h-5 w-5 animate-spin inline-block mr-2" />
                  Loading media...
                </TableCell>
              </TableRow>

              <!-- Empty State -->
              <TableRow v-else-if="data.length === 0">
                <TableCell
                  colspan="4"
                  class="text-center py-10 text-muted-foreground"
                >
                  No media found.
                </TableCell>
              </TableRow>

              <!-- Media Rows -->
              <TableRow
                v-else
                v-for="(media, index) in data"
                :key="media.id"
                :class="{ 'bg-muted/50': dataActive?.id === media.id }"
                class="cursor-pointer hover:bg-muted/50"
                @click="dataActive = media"
              >
                <TableCell>
                  <div class="flex items-center gap-2">
                    <img
                      :src="media.file_path"
                      :alt="media.name"
                      width="50"
                      height="50"
                      class="h-18 w-18 rounded-md object-cover"
                    />
                    <span>{{ media.name }}</span>
                  </div>
                </TableCell>
                <TableCell>{{ media.format }}</TableCell>
                <TableCell>{{ formatSize(media.file_size || 0) }}</TableCell>
                <TableCell>{{ media.width }} x {{ media.height }}</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>

      <!-- Sticky Media Preview -->
      <div
        class="col-span-12 lg:col-span-4 hidden lg:block sticky top-4 h-fit"
        v-if="dataActive?.id"
      >
        <img
          :src="dataActive.file_path"
          :alt="dataActive.name"
          class="aspect-video w-full object-contain bg-secondary"
        />

        <div class="mt-4">
          <a
            :href="dataActive.file_path"
            target="_blank"
            rel="noopener noreferrer"
            class="underline"
          >
            {{ dataActive.name }}
          </a>

          <table class="mt-5">
            <tr
              v-for="item in [
                {
                  key: 'Date Created',
                  value: moment(dataActive.created_at).calendar(),
                },
                { key: 'Format', value: dataActive.format },
                {
                  key: 'File Size',
                  value: formatSize(dataActive.file_size || 0),
                },
                {
                  key: 'Image Size',
                  value: `${dataActive.width} x ${dataActive.height}`,
                },
              ]"
              :key="item.key"
            >
              <td class="text-muted-foreground">
                {{ item.key }}
              </td>
              <td class="w-5"></td>
              <td>
                {{ item.value }}
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped></style>

// app/dashboard/media/page.tsx
"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/atoms/button";
import { Input } from "@/components/atoms/input";
import { Card, CardContent } from "@/components/atoms/card";
import { 
  Upload, 
  Search, 
  Filter, 
  Grid3X3, 
  List, 
  MoreHorizontal,
  Download,
  Trash2,
  Eye,
  Copy,
  Settings
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/atoms/dropdown-menu";
import { MediaUploadDialog } from "@/components/media/media-upload-dialog";
import { MediaPreviewDialog } from "@/components/media/media-preview-dialog";
import { MediaSettingsDialog } from "@/components/media/media-settings-dialog";

interface MediaFile {
  id: string;
  name: string;
  media_type: string;
  file_size: number;
  file_path: string;
  width?: number;
  height?: number;
  alt_text?: string;
  description?: string;
  created_at: string;
  updated_at: string;
}

export default function MediaPage() {
  const [mediaFiles, setMediaFiles] = useState<MediaFile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [selectedFile, setSelectedFile] = useState<MediaFile | null>(null);
  const [isUploadOpen, setIsUploadOpen] = useState(false);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalFiles, setTotalFiles] = useState(0);
  const filesPerPage = 20;

  useEffect(() => {
    fetchMediaFiles();
  }, [currentPage, searchQuery]);

  const fetchMediaFiles = async () => {
    try {
      setIsLoading(true);
      const workspaceId = localStorage.getItem("selectedWorkspace");
      const params = new URLSearchParams({
        page: currentPage.toString(),
        limit: filesPerPage.toString(),
        search: searchQuery,
        workspace_id: workspaceId || "",
      });

      const response = await fetch(`/api/media?${params}`);
      if (!response.ok) throw new Error("Failed to fetch media files");

      const data = await response.json();
      setMediaFiles(data.files);
      setTotalFiles(data.total);
    } catch (error) {
      console.error("Error fetching media files:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleFileUpload = () => {
    fetchMediaFiles();
    setIsUploadOpen(false);
  };

  const handleFileDelete = async (fileId: string) => {
    try {
      const response = await fetch(`/api/media/${fileId}`, {
        method: "DELETE",
      });

      if (!response.ok) throw new Error("Failed to delete file");

      setMediaFiles(files => files.filter(f => f.id !== fileId));
      setSelectedFile(null);
    } catch (error) {
      console.error("Error deleting file:", error);
    }
  };

  const handleCopyUrl = (url: string) => {
    navigator.clipboard.writeText(url);
    // You could add a toast notification here
  };

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const filteredFiles = mediaFiles.filter(file =>
    file.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const totalPages = Math.ceil(totalFiles / filesPerPage);

  return (
    <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Manage Media</h1>
          <p className="text-muted-foreground">
            {totalFiles} files • {Math.ceil(totalFiles / filesPerPage)} pages
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="icon"
            onClick={() => setIsSettingsOpen(true)}
          >
            <Settings className="h-4 w-4" />
          </Button>
          <Button onClick={() => setIsUploadOpen(true)}>
            <Upload className="h-4 w-4 mr-2" />
            Upload
          </Button>
        </div>
      </div>

      {/* Search and Filters */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search files..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10"
          />
        </div>
        <Button variant="outline" size="sm">
          <Filter className="h-4 w-4 mr-2" />
          Filters
        </Button>
        <div className="flex items-center border rounded-md">
          <Button
            variant={viewMode === "grid" ? "default" : "ghost"}
            size="sm"
            onClick={() => setViewMode("grid")}
            className="rounded-r-none"
          >
            <Grid3X3 className="h-4 w-4" />
          </Button>
          <Button
            variant={viewMode === "list" ? "default" : "ghost"}
            size="sm"
            onClick={() => setViewMode("list")}
            className="rounded-l-none"
          >
            <List className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* Media Grid/List */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
        </div>
      ) : viewMode === "grid" ? (
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 gap-4">
          {filteredFiles.map((file) => (
            <Card
              key={file.id}
              className="group cursor-pointer hover:shadow-md transition-shadow"
              onClick={() => {
                setSelectedFile(file);
                setIsPreviewOpen(true);
              }}
            >
              <CardContent className="p-2">
                <div className="aspect-square bg-muted rounded-md mb-2 overflow-hidden relative">
                  {file.media_type.startsWith("image/") ? (
                    <img
                      src={file.file_path}
                      alt={file.alt_text || file.name}
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <div className="text-2xl font-bold text-muted-foreground">
                        {file.name.split('.').pop()?.toUpperCase()}
                      </div>
                    </div>
                  )}
                  <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button
                          variant="secondary"
                          size="icon"
                          className="h-6 w-6"
                          onClick={(e) => e.stopPropagation()}
                        >
                          <MoreHorizontal className="h-3 w-3" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={() => {
                          setSelectedFile(file);
                          setIsPreviewOpen(true);
                        }}>
                          <Eye className="h-4 w-4 mr-2" />
                          Preview
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleCopyUrl(file.file_path)}>
                          <Copy className="h-4 w-4 mr-2" />
                          Copy URL
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Download className="h-4 w-4 mr-2" />
                          Download
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                          onClick={() => handleFileDelete(file.id)}
                          className="text-red-600"
                        >
                          <Trash2 className="h-4 w-4 mr-2" />
                          Delete
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-medium truncate">{file.name}</p>
                  <p className="text-xs text-muted-foreground">
                    {formatFileSize(file.file_size)}
                  </p>
                  {file.width && file.height && (
                    <p className="text-xs text-muted-foreground">
                      {file.width} × {file.height}
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <div className="border rounded-lg">
          <div className="grid grid-cols-6 gap-4 p-4 border-b bg-muted/50 text-sm font-medium">
            <div>Filename</div>
            <div>Format</div>
            <div>File Size</div>
            <div>Image Size</div>
            <div>Date Created</div>
            <div></div>
          </div>
          {filteredFiles.map((file) => (
            <div
              key={file.id}
              className="grid grid-cols-6 gap-4 p-4 border-b hover:bg-muted/50 cursor-pointer"
              onClick={() => {
                setSelectedFile(file);
                setIsPreviewOpen(true);
              }}
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-muted rounded overflow-hidden flex-shrink-0">
                  {file.media_type.startsWith("image/") ? (
                    <img
                      src={file.file_path}
                      alt={file.alt_text || file.name}
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-xs font-bold text-muted-foreground">
                      {file.name.split('.').pop()?.toUpperCase()}
                    </div>
                  )}
                </div>
                <span className="font-medium truncate">{file.name}</span>
              </div>
              <div className="flex items-center text-sm text-muted-foreground">
                {file.media_type}
              </div>
              <div className="flex items-center text-sm">
                {formatFileSize(file.file_size)}
              </div>
              <div className="flex items-center text-sm">
                {file.width && file.height ? `${file.width} × ${file.height}` : "-"}
              </div>
              <div className="flex items-center text-sm text-muted-foreground">
                {formatDate(file.created_at)}
              </div>
              <div className="flex items-center justify-end">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <MoreHorizontal className="h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem onClick={() => {
                      setSelectedFile(file);
                      setIsPreviewOpen(true);
                    }}>
                      <Eye className="h-4 w-4 mr-2" />
                      Preview
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleCopyUrl(file.file_path)}>
                      <Copy className="h-4 w-4 mr-2" />
                      Copy URL
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem
                      onClick={() => handleFileDelete(file.id)}
                      className="text-red-600"
                    >
                      <Trash2 className="h-4 w-4 mr-2" />
                      Delete
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            Showing {((currentPage - 1) * filesPerPage) + 1} to {Math.min(currentPage * filesPerPage, totalFiles)} of {totalFiles} files
          </p>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              disabled={currentPage === 1}
            >
              Previous
            </Button>
            <span className="text-sm">
              Page {currentPage} of {totalPages}
            </span>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
              disabled={currentPage === totalPages}
            >
              Next
            </Button>
          </div>
        </div>
      )}

      {/* Dialogs */}
      <MediaUploadDialog
        open={isUploadOpen}
        onOpenChange={setIsUploadOpen}
        onUploadComplete={handleFileUpload}
      />

      {selectedFile && (
        <MediaPreviewDialog
          open={isPreviewOpen}
          onOpenChange={setIsPreviewOpen}
          file={selectedFile}
          onDelete={() => handleFileDelete(selectedFile.id)}
          onUpdate={fetchMediaFiles}
        />
      )}

      <MediaSettingsDialog
        open={isSettingsOpen}
        onOpenChange={setIsSettingsOpen}
      />
    </div>
  );
}
