// app/(auth)/signup/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/atoms/button";
import { Input } from "@/components/atoms/input";
import { Label } from "@/components/atoms/label";
import OAuthButton from "@/components/forms/oauth-button";
import { GalleryVerticalEnd, Mail } from "lucide-react";
import { supabase } from "@/lib/supabase-client";

export default function SignupPage() {
  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isOtpSent, setIsOtpSent] = useState(false);
  const [otp, setOtp] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();

  const handleEmailSignup = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    try {
      const { error } = await supabase.auth.signInWithOtp({
        email,
        options: {
          emailRedirectTo: `${window.location.origin}/callback`,
        },
      });

      if (error) {
        setError(error.message);
      } else {
        setIsOtpSent(true);
      }
    } catch (error) {
      setError("An unexpected error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  const handleOtpVerification = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    try {
      const { error } = await supabase.auth.verifyOtp({
        email,
        token: otp,
        type: "email",
      });

      if (error) {
        setError(error.message);
      } else {
        router.push("/dashboard");
      }
    } catch (error) {
      setError("An unexpected error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  const resetForm = () => {
    setIsOtpSent(false);
    setOtp("");
    setEmail("");
    setError("");
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-6">
        <div className="flex flex-col items-center gap-2">
          <a
            href="#"
            className="flex flex-col items-center gap-2 font-medium"
          >
            <div className="flex size-8 items-center justify-center rounded-md">
              <GalleryVerticalEnd className="size-6" />
            </div>
            <span className="sr-only">KadoCMS</span>
          </a>
          <h1 className="text-xl font-bold">Create your account</h1>
          <div className="text-center text-sm">
            Already have an account?{" "}
            <a href="/login" className="underline underline-offset-4">
              Sign in
            </a>
          </div>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md text-sm">
            {error}
          </div>
        )}

        <div className="flex flex-col gap-6">
          {!isOtpSent ? (
            <form onSubmit={handleEmailSignup}>
              <div className="grid gap-3">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="m@example.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
              <Button 
                type="submit" 
                className="w-full mt-4" 
                disabled={isLoading || !email}
              >
                {isLoading ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                    Sending...
                  </>
                ) : (
                  <>
                    <Mail className="h-4 w-4 mr-2" />
                    Send Magic Link
                  </>
                )}
              </Button>
            </form>
          ) : (
            <form onSubmit={handleOtpVerification}>
              <div className="grid gap-3">
                <Label htmlFor="otp">Verification Code</Label>
                <Input
                  id="otp"
                  type="text"
                  placeholder="Enter 6-digit code"
                  value={otp}
                  onChange={(e) => setOtp(e.target.value)}
                  maxLength={6}
                  required
                />
                <p className="text-sm text-gray-600">
                  We sent a verification code to {email}
                </p>
              </div>
              <div className="flex gap-2 mt-4">
                <Button 
                  type="submit" 
                  className="flex-1" 
                  disabled={isLoading || otp.length !== 6}
                >
                  {isLoading ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                      Verifying...
                    </>
                  ) : (
                    "Verify & Create Account"
                  )}
                </Button>
                <Button 
                  type="button" 
                  variant="outline" 
                  onClick={resetForm}
                  disabled={isLoading}
                >
                  Back
                </Button>
              </div>
            </form>
          )}

          <div className="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t">
            <span className="bg-background text-muted-foreground relative z-10 px-2">
              Or continue with
            </span>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <OAuthButton provider="github" />
            <OAuthButton provider="google" />
          </div>
        </div>
      </div>

      <div className="text-muted-foreground text-center text-xs text-balance">
        By clicking continue, you agree to our{" "}
        <a href="#" className="underline underline-offset-4 hover:text-primary">
          Terms of Service
        </a>{" "}
        and{" "}
        <a href="#" className="underline underline-offset-4 hover:text-primary">
          Privacy Policy
        </a>
        .
      </div>
    </div>
  );
}

// components/auth/SignUp.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import { Loader2 } from "lucide-vue-next";
import { toast } from "vue-sonner";
import PasswordInput from "~/components/PasswordInput.vue";
import SignInWithGoogleButton from "./sign-in-with-google-button.vue";
import SignInWithFacebookButton from "./sign-in-with-facebook-button.vue";

const supabase = useSupabaseClient();
const router = useRouter();
const loading = ref(false);
const err_message = ref("");

const name = ref("");
const email = ref("");
const password = ref("");
const confirmPassword = ref("");

async function onSubmit(event: Event) {
  event.preventDefault();

  try {
    if (password.value !== confirmPassword.value) {
      err_message.value = "Passwords do not match.";
      return;
    }

    loading.value = true;

    const { error } = await supabase.auth.signUp({
      email: email.value,
      password: password.value,
    });

    if (error) throw error;

    toast.success("Check your email for the confirmation link.");
    err_message.value = "";
    router.push("/login");
  } catch (error) {
    if (error instanceof Error) {
      err_message.value = error.message;
    } else {
      err_message.value = "An unknown error occurred.";
    }
  } finally {
    loading.value = false;
  }
}

watch(err_message, (err) => {
  if (err) toast.error(err);
});
</script>

<template>
  <div :class="cn('grid gap-6', $attrs.class ?? '')">
    <form @submit="onSubmit">
      <div class="grid gap-4">
        <div class="grid gap-2">
          <Label for="name"> Name </Label>
          <Input
            id="name"
            v-model="name"
            placeholder="Enter your name"
            type="text"
            auto-capitalize="none"
            auto-complete="name"
            auto-correct="off"
            :disabled="loading"
          />
        </div>
        <div class="grid gap-2">
          <Label for="email"> Email </Label>
          <Input
            id="email"
            v-model="email"
            placeholder="name@example.com"
            type="email"
            auto-capitalize="none"
            auto-complete="email"
            auto-correct="off"
            :disabled="loading"
          />
        </div>
        <div class="grid gap-2">
          <Label for="password"> Password </Label>
          <PasswordInput id="password" v-model="password" />
        </div>
        <div class="grid gap-2">
          <Label for="confirm-password"> Confirm Password </Label>
          <PasswordInput id="confirm-password" v-model="confirmPassword" />
        </div>
        <Button :disabled="loading">
          <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
          Sign In with Email
        </Button>
      </div>
    </form>
    <Separator label="Or continue with" />
    <div class="flex items-center gap-4">
      <SignInWithFacebookButton />
      <SignInWithGoogleButton />
    </div>
  </div>
</template>
